// From:
// https://developers.cloudflare.com/basin-sql/sql-reference/
// https://developers.cloudflare.com/basin-sql/sql-reference/scalar-functions/
// https://developers.cloudflare.com/basin-sql/sql-reference/complex-types/
// Date: 2026-06-08
export default [
    // Statement and schema keywords
    'DATABASES',
    'DESCRIBE',
    'EXPLAIN',
    'NAMESPACES',
    'SELECT',
    'SHOW',
    'TABLES',
    'WITH',

    // Clause and modifier keywords
    'ALL',
    'AS',
    'ASC',
    'BY',
    'CROSS',
    'CUBE',
    'DESC',
    'DISTINCT',
    'EXCEPT',
    'FORMAT',
    'FROM',
    'FULL',
    'GROUP',
    'GROUPING',
    'HAVING',
    'INNER',
    'INTERSECT',
    'JOIN',
    'JSON',
    'LEFT',
    'LIMIT',
    'ON',
    'ORDER',
    'OUTER',
    'OVER',
    'PARTITION',
    'QUALIFY',
    'RIGHT',
    'ROLLUP',
    'SETS',
    'UNION',
    'WHERE',

    // Predicate and logical keywords
    'AND',
    'BETWEEN',
    'EXISTS',
    'FALSE',
    'ILIKE',
    'IN',
    'IS',
    'LIKE',
    'NOT',
    'NULL',
    'OR',
    'SIMILAR',
    'TO',
    'TRUE',
    'UNKNOWN',

    // Expression keywords
    'CASE',
    'CAST',
    'DAY',
    'ELSE',
    'END',
    'EXTRACT',
    'FOR',
    'INTERVAL',
    'MONTH',
    'PLACING',
    'THEN',
    'TRY_CAST',
    'WHEN',
    'YEAR',

    // Type keywords
    'ARRAY',
    'BIGINT',
    'BOOLEAN',
    'BYTEA',
    'CHAR',
    'DATE',
    'DOUBLE',
    'FLOAT',
    'INT',
    'INTEGER',
    'MAP',
    'REAL',
    'STRING',
    'STRUCT',
    'TEXT',
    'TIMESTAMP',
    'TIMESTAMPTZ',
    'VARCHAR',

    // Common combinations
    'CASE WHEN',
    'CROSS JOIN',
    'DISTINCT ON',
    'FULL OUTER JOIN',
    'GROUP BY CUBE',
    'GROUP BY GROUPING SETS',
    'GROUP BY ROLLUP',
    'GROUP BY',
    'INNER JOIN',
    'IS FALSE',
    'IS NOT FALSE',
    'IS NOT NULL',
    'IS NOT TRUE',
    'IS NOT UNKNOWN',
    'IS NULL',
    'IS TRUE',
    'IS UNKNOWN',
    'LEFT JOIN',
    'NOT EXISTS',
    'NOT BETWEEN',
    'NOT ILIKE',
    'NOT IN',
    'NOT LIKE',
    'ORDER BY',
    'PARTITION BY',
    'RIGHT JOIN',
    'SELECT DISTINCT',
    'SELECT DISTINCT ON',
    'SELECT *',
    'SELECT * FROM',
    'SELECT COUNT(*)',
    'SELECT COUNT(*) FROM',
    'UNION ALL',
    'EXPLAIN FORMAT JSON',
    'SHOW DATABASES',
    'SHOW NAMESPACES',
    'SHOW TABLES',
    'SHOW TABLES IN',
    'SIMILAR TO'
]
