// From: SELECT * FROM system.keywords;
export default [
    'ADD COLUMN',
    'ADD CONSTRAINT',
    'ADD INDEX',
    'ADD PROJECTION',
    'ADD STATISTIC',
    'ADD',
    'ADMIN OPTION FOR',
    'AFTER',
    'ALGORITHM',
    'ALIAS',
    'ALL',
    'ALTER COLUMN',
    'ALTER DATABASE',
    'ALTER LIVE VIEW',
    'ALTER POLICY',
    'ALTER PROFILE',
    'ALTER QUOTA',
    'ALTER ROLE',
    'ALTER ROW POLICY',
    'ALTER SETTINGS PROFILE',
    'ALTER TABLE',
    'ALTER TEMPORARY TABLE',
    'ALTER USER',
    'ALTER',
    'AND STDOUT',
    'AND',
    'ANTI',
    'ANY',
    'APPEND',
    'APPLY DELETED MASK',
    'APPLY',
    'ARRAY JOIN',
    'AS',
    'ASC',
    'ASCENDING',
    'ASOF',
    'ASSUME',
    'AST',
    'ASYNC',
    'ATTACH PART',
    'ATTACH PARTITION',
    'ATTACH POLICY',
    'ATTACH PROFILE',
    'ATTACH QUOTA',
    'ATTACH ROLE',
    'ATTACH ROW POLICY',
    'ATTACH SETTINGS PROFILE',
    'ATTACH USER',
    'ATTACH',
    'AZURE',
    'BACKUP',
    'bagexpansion',
    'BEGIN TRANSACTION',
    'BETWEEN',
    'BIDIRECTIONAL',
    'BOTH',
    'BY',
    'CASCADE',
    'CASE',
    'CAST',
    'CHANGE',
    'CHANGED',
    'CHAR VARYING',
    'CHAR',
    'CHARACTER LARGE OBJECT',
    'CHARACTER VARYING',
    'CHARACTER',
    'CHECK ALL TABLES',
    'CHECK TABLE',
    'CHECK',
    'CLEANUP',
    'CLEAR COLUMN',
    'CLEAR INDEX',
    'CLEAR PROJECTION',
    'CLEAR STATISTIC',
    'CLUSTER',
    'CLUSTERS',
    'CN',
    'CODEC',
    'COLLATE',
    'COLUMN',
    'COLUMNS',
    'COMMENT COLUMN',
    'COMMENT',
    'COMMIT',
    'COMPRESSION',
    'CONST',
    'CONSTRAINT',
    'CREATE POLICY',
    'CREATE PROFILE',
    'CREATE QUOTA',
    'CREATE ROLE',
    'CREATE ROW POLICY',
    'CREATE SETTINGS PROFILE',
    'CREATE TABLE',
    'CREATE TEMPORARY TABLE',
    'CREATE USER',
    'CREATE',
    'CROSS',
    'CUBE',
    'CURRENT GRANTS',
    'CURRENT QUOTA',
    'CURRENT ROLES',
    'CURRENT ROW',
    'CURRENT TRANSACTION',
    'CURRENTUSER',
    'D',
    'DATABASE',
    'DATABASES',
    'DATE',
    'DAY',
    'DAYS',
    'DD',
    'DEDUPLICATE',
    'DEFAULT DATABASE',
    'DEFAULT ROLE',
    'DEFAULT',
    'DEFINER',
    'DELETE',
    'DEPENDS ON',
    'DESC',
    'DESCENDING',
    'DESCRIBE',
    'DETACH PART',
    'DETACH PARTITION',
    'DETACH',
    'DICTIONARIES',
    'DICTIONARY',
    'DISK',
    'DISTINCT ON',
    'DISTINCT',
    'DIV',
    'DROP COLUMN',
    'DROP CONSTRAINT',
    'DROP DEFAULT',
    'DROP DETACHED PART',
    'DROP DETACHED PARTITION',
    'DROP INDEX',
    'DROP PART',
    'DROP PARTITION',
    'DROP PROJECTION',
    'DROP STATISTIC',
    'DROP TABLE',
    'DROP TEMPORARY TABLE',
    'DROP',
    'ELSE',
    'EMPTY AS',
    'EMPTY',
    'ENABLED ROLES',
    'END',
    'ENFORCED',
    'ENGINE',
    'EPHEMERAL SEQUENTIAL',
    'EPHEMERAL',
    'ESTIMATE',
    'EVENT',
    'EVENTS',
    'EVERY',
    'EXCEPT DATABASE',
    'EXCEPT DATABASES',
    'EXCEPT TABLE',
    'EXCEPT TABLES',
    'EXCEPT',
    'EXCHANGE DICTIONARIES',
    'EXCHANGE TABLES',
    'EXISTS',
    'EXPLAIN',
    'EXPRESSION',
    'EXTENDED',
    'EXTERNAL DDL FROM',
    'FALSE',
    'FETCH PART',
    'FETCH PARTITION',
    'FETCH',
    'FIELDS',
    'FILE',
    'FILESYSTEM CACHE',
    'FILESYSTEM CACHES',
    'FILTER',
    'FINAL',
    'FIRST',
    'FOLLOWING',
    'FOR',
    'FOREIGN KEY',
    'FOREIGN',
    'FORGET PARTITION',
    'FORMAT',
    'FREEZE',
    'FROM INFILE',
    'FROM SHARD',
    'FROM',
    'FULL',
    'FULLTEXT',
    'FUNCTION',
    'GLOBAL IN',
    'GLOBAL NOT IN',
    'GLOBAL',
    'GRANT OPTION FOR',
    'GRANT',
    'GRANTEES',
    'GRANULARITY',
    'GROUP BY',
    'GROUPING SETS',
    'GROUPS',
    'H',
    'HASH',
    'HAVING',
    'HDFS',
    'HH',
    'HIERARCHICAL',
    'HOST',
    'HOUR',
    'HOURS',
    'HTTP',
    'ID',
    'IDENTIFIED',
    'IF EMPTY',
    'IF EXISTS',
    'IF NOT EXISTS',
    'IGNORE NULLS',
    'ILIKE',
    'IN PARTITION',
    'IN',
    'INDEX',
    'INDEXES',
    'INDICES',
    'INHERIT',
    'INJECTIVE',
    'INNER',
    'INSERT',
    'INTO',
    'INSERT INTO',
    'INTERPOLATE',
    'INTERSECT',
    'INTERVAL',
    'INTO OUTFILE',
    'INVISIBLE',
    'INVOKER',
    'IP',
    'IS NOT DISTINCT FROM',
    'IS NOT NULL',
    'IS NULL',
    'JOIN',
    'KERBEROS',
    'KEY BY',
    'KEY',
    'KEYED BY',
    'KEYS',
    'KILL',
    'KIND',
    'LARGE OBJECT',
    'LAST',
    'LAYOUT',
    'LDAP',
    'LEADING',
    'LEFT ARRAY JOIN',
    'LEFT',
    'LESS THAN',
    'LEVEL',
    'LIFETIME',
    'LIGHTWEIGHT',
    'LIKE',
    'LIMIT',
    'LINEAR',
    'LIST',
    'LIVE',
    'LOCAL',
    'M',
    'MATCH',
    'MATERIALIZE COLUMN',
    'MATERIALIZE INDEX',
    'MATERIALIZE PROJECTION',
    'MATERIALIZE STATISTIC',
    'MATERIALIZE TTL',
    'MATERIALIZE',
    'MATERIALIZED',
    'MAX',
    'MCS',
    'MEMORY',
    'MERGES',
    'MI',
    'MICROSECOND',
    'MICROSECONDS',
    'MILLISECOND',
    'MILLISECONDS',
    'MIN',
    'MINUTE',
    'MINUTES',
    'MM',
    'MOD',
    'MODIFY COLUMN',
    'MODIFY COMMENT',
    'MODIFY DEFINER',
    'MODIFY ORDER BY',
    'MODIFY QUERY',
    'MODIFY REFRESH',
    'MODIFY SAMPLE BY',
    'MODIFY SETTING',
    'MODIFY SQL SECURITY',
    'MODIFY TTL',
    'MODIFY',
    'MONTH',
    'MONTHS',
    'MOVE PART',
    'MOVE PARTITION',
    'MOVE',
    'MS',
    'MUTATION',
    'N',
    'NAME',
    'NAMED COLLECTION',
    'NANOSECOND',
    'NANOSECONDS',
    'NEXT',
    'NO ACTION',
    'NO DELAY',
    'NO LIMITS',
    'NONE',
    'NOT BETWEEN',
    'NOT IDENTIFIED',
    'NOT ILIKE',
    'NOT IN',
    'NOT KEYED',
    'NOT LIKE',
    'NOT OVERRIDABLE',
    'NOT',
    'NS',
    'NULL',
    'NULLS',
    'OFFSET',
    'ON DELETE',
    'ON UPDATE',
    'ON VOLUME',
    'ON',
    'ONLY',
    'OPTIMIZE TABLE',
    'OR REPLACE',
    'OR',
    'ORDER',
    'ORDER BY',
    'OUTER',
    'OVER',
    'OVERRIDABLE',
    'PART',
    'PARTIAL',
    'PARTITION BY',
    'PARTITION',
    'PARTITIONS',
    'PASTE',
    'PERIODIC REFRESH',
    'PERMANENTLY',
    'PERMISSIVE',
    'PERSISTENT SEQUENTIAL',
    'PERSISTENT',
    'PIPELINE',
    'PLAN',
    'POPULATE',
    'PRECEDING',
    'PRECISION',
    'PREWHERE',
    'PRIMARY KEY',
    'PRIMARY',
    'PROFILE',
    'PROJECTION',
    'Protobuf',
    'PULL',
    'Q',
    'QQ',
    'QUARTER',
    'QUARTERS',
    'QUERY TREE',
    'QUERY',
    'QUOTA',
    'RANDOMIZE FOR',
    'RANDOMIZED',
    'RANGE',
    'READONLY',
    'REALM',
    'RECOMPRESS',
    'REFERENCES',
    'REFRESH',
    'REGEXP',
    'REMOVE SAMPLE BY',
    'REMOVE TTL',
    'REMOVE',
    'RENAME COLUMN',
    'RENAME DATABASE',
    'RENAME DICTIONARY',
    'RENAME TABLE',
    'RENAME TO',
    'RENAME',
    'REPLACE PARTITION',
    'REPLACE',
    'RESET SETTING',
    'RESPECT NULLS',
    'RESTORE',
    'RESTRICT',
    'RESTRICTIVE',
    'RESUME',
    'REVOKE',
    'RIGHT',
    'ROLLBACK',
    'ROLLUP',
    'ROW',
    'ROWS',
    'S',
    'S3',
    'SALT',
    'SAMPLE BY',
    'SAMPLE',
    'SCHEME',
    'SECOND',
    'SECONDS',
    'SELECT',
    'SEMI',
    'SERVER',
    'SET DEFAULT ROLE',
    'SET DEFAULT',
    'SET FAKE TIME',
    'SET NULL',
    'SET ROLE DEFAULT',
    'SET ROLE',
    'SET TRANSACTION SNAPSHOT',
    'SET',
    'SETTINGS',
    'SHOW ACCESS',
    'SHOW CREATE',
    'SHOW ENGINES',
    'SHOW FUNCTIONS',
    'SHOW GRANTS',
    'SHOW PRIVILEGES',
    'SHOW PROCESSLIST',
    'SHOW SETTING',
    'SHOW',
    'SIGNED',
    'SIMPLE',
    'SOURCE',
    'SPATIAL',
    'SQL SECURITY',
    'SS',
    'START TRANSACTION',
    'STATISTIC',
    'STEP',
    'STORAGE',
    'STRICT',
    'SUBPARTITION BY',
    'SUBPARTITION',
    'SUBPARTITIONS',
    'SUSPEND',
    'SYNC',
    'SYNTAX',
    'SYSTEM',
    'TABLE OVERRIDE',
    'TABLE',
    'TABLES',
    'TEMPORARY TABLE',
    'TEMPORARY',
    'TEST',
    'THEN',
    'TIMESTAMP',
    'TO DISK',
    'TO INNER UUID',
    'TO SHARD',
    'TO TABLE',
    'TO VOLUME',
    'TO',
    'TOP',
    'TOTALS',
    'TRACKING ONLY',
    'TRAILING',
    'TRANSACTION',
    'TRIGGER',
    'TRUE',
    'TRUNCATE',
    'TTL',
    'TYPE',
    'TYPEOF',
    'UNBOUNDED',
    'UNDROP',
    'UNFREEZE',
    'UNION',
    'UNIQUE',
    'UNSET FAKE TIME',
    'UNSIGNED',
    'UPDATE',
    'URL',
    'USE',
    'USING',
    'UUID',
    'VALID UNTIL',
    'VALUES',
    'VARYING',
    'VIEW',
    'VISIBLE',
    'WATCH',
    'WATERMARK',
    'WEEK',
    'WEEKS',
    'WHEN',
    'WHERE',
    'WINDOW',
    'QUALIFY',
    'WITH ADMIN OPTION',
    'WITH CHECK',
    'WITH FILL',
    'WITH GRANT OPTION',
    'WITH NAME',
    'WITH REPLACE OPTION',
    'WITH TIES',
    'WITH',
    'RECURSIVE',
    'WK',
    'WRITABLE',
    'WW',
    'YEAR',
    'YEARS',
    'YY',
    'YYYY',
    'ZKPATH',
    'ALLOWED_LATENESS',
    'AUTO_INCREMENT',
    'base_backup',
    'BCRYPT_HASH',
    'BCRYPT_PASSWORD',
    'CHANGEABLE_IN_READONLY',
    'cluster_host_ids',
    'CURRENT_USER',
    'DOUBLE_SHA1_HASH',
    'DOUBLE_SHA1_PASSWORD',
    'IS_OBJECT_ID',
    'NO_PASSWORD',
    'PART_MOVE_TO_SHARD',
    'PLAINTEXT_PASSWORD',
    'SHA256_HASH',
    'SHA256_PASSWORD',
    'SQL_TSI_DAY',
    'SQL_TSI_HOUR',
    'SQL_TSI_MICROSECOND',
    'SQL_TSI_MILLISECOND',
    'SQL_TSI_MINUTE',
    'SQL_TSI_MONTH',
    'SQL_TSI_NANOSECOND',
    'SQL_TSI_QUARTER',
    'SQL_TSI_SECOND',
    'SQL_TSI_WEEK',
    'SQL_TSI_YEAR',
    'SSH_KEY',
    'SSL_CERTIFICATE',
    'STRICTLY_ASCENDING',
    'WITH_ITEMINDEX'
]
