// Common SQL combination keywords
// TODO:
// Should differentiate by database, e.g. SQLite doesn't support CREATE DATABASE, while Postgres also supports CREATE TYPE, CREATE SCHEMA
// For some time-series databases, indexes and primary keys don't exist at all
export default [
    'ADD COLUMN',
    'ALTER COLUMN',
    'ALTER TABLE',
    'CREATE DATABASE',
    'CREATE INDEX',
    'CREATE PROCEDURE',
    'CREATE TABLE',
    'CREATE TRIGGER',
    'CREATE UNIQUE INDEX',
    'CREATE VIEW',
    'CREATE VIRTUAL TABLE',
    'DEFAULT VALUE',
    'DROP COLUMN',
    'DROP CONSTRAINT',
    'DROP DATABASE',
    'DROP DEFAULT',
    'DROP INDEX',
    'DROP TABLE',
    'DROP TRIGGER',
    'DROP VIEW',
    'FOREIGN KEY',
    'NOT NULL',
    'PRIMARY KEY',
    'RENAME COLUMN',
    'TRUNCATE TABLE',

    'DELETE FROM',
    'INSERT INTO',
    'SELECT *',
    'SELECT * FROM',
    'SELECT COUNT(*)',
    'SELECT COUNT(*) FROM',
    'SELECT DISTINCT',
    'UNION ALL',
    'UPDATE SET',

    'CASE WHEN',
    'GROUP BY',
    'IS NOT NULL',
    'IS NULL',
    'NOT BETWEEN',
    'NOT IN',
    'NOT LIKE',
    'ON CONFLICT',
    'ON DELETE',
    'ON UPDATE',
    'ORDER BY',
    'WHERE EXISTS',
    'WHERE NOT EXISTS',

    'CROSS JOIN',
    'FULL JOIN',
    'FULL OUTER JOIN',
    'INNER JOIN',
    'LEFT JOIN',
    'LEFT OUTER JOIN',
    'OUTER JOIN',
    'RIGHT JOIN',
    'RIGHT OUTER JOIN',

    'BEGIN TRANSACTION',
    'COMMIT TRANSACTION',
    'ROLLBACK TRANSACTION'
]
