// Date: 2026-04-10
export default [
    // https://manual.manticoresearch.com/Functions/Mathematical_functions
    'ABS',
    'ATAN2',
    'BITDOT',
    'CEIL',
    'COS',
    'CRC32',
    'EXP',
    'FIBONACCI',
    'FLOOR',
    'GREATEST',
    'IDIV',
    'LEAST',
    'LN',
    'LOG10',
    'LOG2',
    'MAX',
    'MIN',
    'POW',
    'RAND',
    'SIN',
    'SQRT',
    // https://manual.manticoresearch.com/Functions/Searching_and_ranking_functions
    'BM25A',
    'BM25F',
    'EXIST',
    'MIN_TOP_SORTVAL',
    'MIN_TOP_WEIGHT',
    'PACKEDFACTORS',
    'REMOVE_REPEATS',
    'WEIGHT',
    'ZONESPANLIST',
    'QUERY',
    // https://manual.manticoresearch.com/Functions/Type_casting_functions
    'BIGINT',
    'DOUBLE',
    'INTEGER',
    'TO_STRING',
    'UINT',
    'UINT64',
    'SINT',
    // https://manual.manticoresearch.com/Functions/Arrays_and_conditions_functions
    'ALL',
    'ANY',
    'CONTAINS',
    'IF',
    'HISTOGRAM',
    'IN',
    'INDEXOF',
    'INTERVAL',
    'LENGTH',
    'RANGE',
    'REMAP',
    // https://manual.manticoresearch.com/Functions/Date_and_time_functions
    'NOW',
    'CURTIME',
    'CURDATE',
    'UTC_TIME',
    'UTC_TIMESTAMP',
    'SECOND',
    'MINUTE',
    'HOUR',
    'DAY',
    'MONTH',
    'QUARTER',
    'YEAR',
    'DAYNAME',
    'MONTHNAME',
    'DAYOFWEEK',
    'DAYOFYEAR',
    'YEARWEEK',
    'YEARMONTH',
    'YEARMONTHDAY',
    'TIMEDIFF',
    'DATEDIFF',
    'DATE',
    'TIME',
    'DATE_FORMAT',
    'DATE_HISTOGRAM',
    'DATE_RANGE',
    // https://manual.manticoresearch.com/Functions/Geo_spatial_functions
    'GEODIST',
    'GEOPOLY2D',
    'POLY2D',
    // https://manual.manticoresearch.com/Functions/String_functions
    'CONCAT',
    'LEVENSHTEIN',
    'REGEX',
    'SNIPPET',
    'SUBSTRING_INDEX',
    'UPPER',
    'LOWER',
    // https://manual.manticoresearch.com/Functions/Other_functions
    'CONNECTION_ID',
    'HYBRID_SCORE',
    'KNN_DIST',
    'LAST_INSERT_ID',
    'UUID_SHORT'
]
