// No specific keyword documentation or SQL query to get all keywords
// These are compiled by AI from the official Statements and Operators documentation pages
// https://developers.cloudflare.com/analytics/analytics-engine/sql-reference/statements/
// https://developers.cloudflare.com/analytics/analytics-engine/sql-reference/operators/
// Date: 2026-08-08
export default [
    'SHOW',
    'TABLES',
    'FORMAT',
    'TIMEZONES',
    'TIMEZONE',
    'SELECT',
    'FROM',
    'WHERE',
    'GROUP',
    'BY',
    'GROUP BY',
    'ORDER',
    'ORDER BY',
    'LIMIT',
    'ALL',
    'OFFSET',
    'AS',
    'ASC',
    'DESC',
    'DISTINCT',
    'OR',
    'IN',
    'AND',
    'NOT',
    'NOT IN',
    'HAVING',
    'BETWEEN',
    'NOT BETWEEN',
    'LIKE',
    'NOT LIKE',
    'ILIKE',
    'NOT ILIKE',
    'TRUE',
    'FALSE',
    'INTERVAL',
    'YEAR',
    'MONTH',
    'DAY',
    'HOUR',
    'MINUTE',
    'SECOND'
]
