// Workers Analytics Engine columns are fixed
// From: https://developers.cloudflare.com/analytics/analytics-engine/sql-api/#table-structure
// Date: 2026-01-10
export default [
    { name: 'dataset', type: 'string' },
    { name: 'timestamp', type: 'DateTime' },
    { name: '_sample_interval', type: 'integer' },
    { name: 'index1', type: 'string' },
    { name: 'blob1', type: 'string' },
    { name: 'blob2', type: 'string' },
    { name: 'blob3', type: 'string' },
    { name: 'blob4', type: 'string' },
    { name: 'blob5', type: 'string' },
    { name: 'blob6', type: 'string' },
    { name: 'blob7', type: 'string' },
    { name: 'blob8', type: 'string' },
    { name: 'blob9', type: 'string' },
    { name: 'blob10', type: 'string' },
    { name: 'blob11', type: 'string' },
    { name: 'blob12', type: 'string' },
    { name: 'blob13', type: 'string' },
    { name: 'blob14', type: 'string' },
    { name: 'blob15', type: 'string' },
    { name: 'blob16', type: 'string' },
    { name: 'blob17', type: 'string' },
    { name: 'blob18', type: 'string' },
    { name: 'blob19', type: 'string' },
    { name: 'blob20', type: 'string' },
    { name: 'double1', type: 'double' },
    { name: 'double2', type: 'double' },
    { name: 'double3', type: 'double' },
    { name: 'double4', type: 'double' },
    { name: 'double5', type: 'double' },
    { name: 'double6', type: 'double' },
    { name: 'double7', type: 'double' },
    { name: 'double8', type: 'double' },
    { name: 'double9', type: 'double' },
    { name: 'double10', type: 'double' },
    { name: 'double11', type: 'double' },
    { name: 'double12', type: 'double' },
    { name: 'double13', type: 'double' },
    { name: 'double14', type: 'double' },
    { name: 'double15', type: 'double' },
    { name: 'double16', type: 'double' },
    { name: 'double17', type: 'double' },
    { name: 'double18', type: 'double' },
    { name: 'double19', type: 'double' },
    { name: 'double20', type: 'double' }
]
