// From: https://developers.cloudflare.com/analytics/analytics-engine/sql-reference/
// Date: 2026-01-10
export default [
    // Aggregate functions
    'count',
    'sum',
    'avg',
    'min',
    'max',
    'quantileExactWeighted',
    'quantileWeighted',
    'argMax',
    'argMin',
    'first_value',
    'last_value',
    'topK',
    'topKWeighted',
    'countIf',
    'sumIf',
    'avgIf',
    // Bit functions
    'bitAnd',
    'bitCount',
    'bitHammingDistance',
    'bitNot',
    'bitOr',
    'bitRotateLeft',
    'bitRotateRight',
    'bitShiftLeft',
    'bitShiftRight',
    'bitTest',
    'bitXor',
    // Conditional functions
    'if',
    // Date and Time functions
    'formatDateTime',
    'now',
    'toDateTime',
    'toYear',
    'toMonth',
    'toDayOfWeek',
    'toDayOfMonth',
    'toHour',
    'toMinute',
    'toSecond',
    'toUnixTimestamp',
    'toStartOfInterval',
    'toStartOfYear',
    'toStartOfMonth',
    'toStartOfWeek',
    'toStartOfDay',
    'toStartOfHour',
    'toStartOfFifteenMinutes',
    'toStartOfTenMinutes',
    'toStartOfFiveMinutes',
    'toStartOfMinute',
    'toYYYYMM',
    // Encoding functions
    'bin',
    'hex',
    // Mathematical functions
    'intDiv',
    'log',
    'ln',
    'pow',
    'round',
    'floor',
    'ceil',
    // String functions
    'length',
    'empty',
    'lower',
    'lowerUTF8',
    'upper',
    'upperUTF8',
    'startsWith',
    'endsWith',
    'position',
    'substring',
    'format',
    'extract',
    // Type conversion functions
    'toUInt8',
    'toUInt32'
]
