name: 💬 Question
title: "[Question] "
description: Ask a question
labels: ["question"]

body:
  - type: textarea
    id: question
    attributes:
      label: What is your question?
      description: "Describe what you want to know about"
    validations:
      required: true
