export { emit, listen } from '@tauri-apps/api/event'
export type { UnlistenFn } from '@tauri-apps/api/event'

export const REFRESH_CONNECTIONS = 'refresh-connections'
export const REFRESH_EDITOR_FONT_OPTIONS = 'refresh-editor-font-options'
export const REFRESH_BYTES_FORMAT = 'refresh-bytes-format'
export const LICENSE_ACTIVATE_SUCCESS = 'license-activate-success'
export const REFRESH_TRANSLATION = 'refresh-translation'
export const REFRESH_TRANSFORM_RULES = 'refresh-transform-rules'
export const REFRESH_AI_MODELS = 'refresh-ai-models'
export const REFRESH_AGENTS = 'refresh-agents'
export const SWITCH_SETTINGS_TAB = 'switch-settings-tab'
